name: book-generate-pdf
run-name: "Generate Book PDF"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  BOOK_SOURCE_ROOT: ${{ github.workspace }}/book
  BOOK_BUILD_ROOT: ${{ github.workspace }}/build

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor
      volumes:
        - ${{ github.workspace }}:/documents
    steps:
      - uses: actions/checkout@v4
      - name: "asciidoctor-pdf (Spanish)"
        run: |
          asciidoctor-pdf \
            -a pdf-themesdir=$BOOK_SOURCE_ROOT/themes \
            -a pdf-theme=basic \
            -a pdf-fontsdir=$BOOK_SOURCE_ROOT/fonts \
            -o $BOOK_BUILD_ROOT/vsm-fuentemilanos.pdf \
            $BOOK_SOURCE_ROOT/es/index.adoc
      - name: "asciidoctor-pdf (English)"
        run: |
          asciidoctor-pdf \
            -a pdf-themesdir=$BOOK_SOURCE_ROOT/themes \
            -a pdf-theme=basic \
            -a pdf-fontsdir=$BOOK_SOURCE_ROOT/fonts \
            -o $BOOK_BUILD_ROOT/vsm-fuentemilanos_en.pdf \
            $BOOK_SOURCE_ROOT/en/index.adoc
      - name: "Save generated books as build artifact"
        uses: actions/upload-artifact@v4
        with:
          name: book
          path: build
